FROM node:latest
MAINTAINER Tiago Pires <tandrepires@gmail.com>

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

ADD /usr/local/share/man /usr/local/share/man
ADD /usr/local/bin /usr/local/bin
ADD /usr/local/lib/node /usr/local/lib/node
ADD /usr/local/lib/node_modules /usr/local/lib/node_modules
ADD /usr/local/include/node /usr/local/include/node

RUN echo "developer:x:UID:GID:Developer,,,:/yod-dev:/bin/bash" >> /etc/passwd && \
	echo "developer:x:GID:" >> /etc/group

RUN apt-get update && \ 
	apt-get install -y ruby-full xdg-utils w3m && \ 
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    gem install sass compass && \
    npm install -g grunt-cli bower gulp && \
    mkdir /yod-dev && \
    chown -R UID:GID /yod-dev

USER developer
ENV HOME /yod-dev

WORKDIR /yod-dev
