#!/bin/bash
YOD_HOME=/yod-setup
MIN_VER=1.3.1
PROJECT_NAME=${PWD##*/}
SCRIPTS_DIR=${SCRIPTS_DIR:-/usr/local/bin}
YOD_UID=$(id -u)
YOD_GID=$(id -g)
PWD=${PWD}

if [[ "$OSTYPE" == "darwin"* ]]; then
	function _version_check {
	        ver=`echo -ne "$1\n$2" |sort -r |head -n1`
	        if [ "$2" == "$1" ]; then
	                return 1
	        elif [ "$2" == "$ver" ]; then
	                return 0
	        else
	                return 1
	        fi
	}

	echo "Detected docker on Mac OS X."

	if _version_check `docker --version | awk {'print $3'} | sed "s|,||g"` $MIN_VER; then
	        echo "Error: You need to upgrade your boot2docker to $MIN_VER."
	        exit 1
	fi

	if [[ "$PWD" != "/Users"* ]]; then
		echo "Shared volumes only work under /Users. Please create your directory under /Users directory and run yod again."
		exit 1
	fi

	if [ $(echo $PATH | grep $HOME/bin | wc -l) -eq 0 ]; then
	    echo -e "#Added by yod\nexport PATH=\$PATH:$HOME/bin" >> $HOME/.profile
	    source $HOME/.profile
		echo -e "Added to your $HOME/.profile:\n\n\texport PATH=\$PATH:$HOME/bin"
	fi
	
	SCRIPTS_DIR=$HOME/bin
	YOD_UID=1000
	YOD_GID=50

elif [[ "$OSTYPE" == "win32" ]]; then
    echo "Sorry, but yod doesn't work on Windows. For now."
    exit 1
fi

docker run -it --rm -v /var/run/docker.sock:/docker.sock -v $SCRIPTS_DIR:/scripts -v $PWD:$YOD_HOME/$PROJECT_NAME -v $HOME/.config:/$YOD_HOME/.config -e UID=$YOD_UID -e GID=$YOD_GID -e PROJECT_NAME=$PROJECT_NAME yod /bin/bash $YOD_HOME/setup.sh $1
